import { EntityMapConfig } from "../../adapters/postgres/repositories/Repository";

export const EmployeeMapperEntity: EntityMapConfig = {
  fields: [
    { dbField: "id", entityField: "id" },
    { dbField: "nik", entityField: "nik" },
    { dbField: "name", entityField: "name" },
    { dbField: "phone", entityField: "phone" },
    { dbField: "address", entityField: "address" },
    { dbField: "province_id", entityField: "provinceId" },
    { dbField: "city_id", entityField: "cityId" },
    { dbField: "district_id", entityField: "districtId" },
    { dbField: "subdistrict_id", entityField: "subdistrictId" },
    { dbField: "merital_status", entityField: "meritalStatus" },
    { dbField: "religion", entityField: "religion" },
    { dbField: "birth_date", entityField: "birthDate" },
    { dbField: "birth_place", entityField: "birthPlace" },
    { dbField: "blood_type", entityField: "bloodType" },
    { dbField: "rt", entityField: "rt" },
    { dbField: "rw", entityField: "rw" },
    { dbField: "work_type", entityField: "workType" },
    { dbField: "position", entityField: "position" },
    { dbField: "notes", entityField: "notes" },
    { dbField: "image_path", entityField: "imagePath" },
    { dbField: "gender", entityField: "gender" },
    { dbField: "hire_date", entityField: "hireDate" },
    { dbField: "is_active", entityField: "isActive" },
    { dbField: "createdAt", entityField: "createdAt" },
    { dbField: "updatedAt", entityField: "updatedAt" },
  ],
  relations: [],
};
